---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test
    Operator: <%= ENV['USER'] %>

transport:
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver:
      tags:
        Name: archiva-default-ubuntu-12.04
      image_id: ami-dfd6d7b5

  - name: ubuntu-14.04
    driver:
      tags:
        Name: archiva-default-ubuntu-14.04
      image_id: ami-7d7d7c17

  - name: debian-7
    driver:
      tags:
        Name: archiva-default-debian-7
      image_id: ami-e0efab88
    transport:
      username: admin

suites:
  - name: default
    run_list:
      - recipe[archiva::nginx_proxy]
