---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.2.0

suites:
  - name: default
    run_list:
      - recipe[archiva::nginx_proxy]
