---
driver:
  name: dokken
  chef_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  privileged: true  # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: false

verifier:
  name: inspec
  chef_license: accept

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
  - name: debian-10
    driver:
      image: dokken/debian-10
      pid_one_command: /bin/systemd

suites:
  - name: default
    run_list:
      - recipe[archiva::nginx_proxy]
