---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-9
  - name: debian-10

suites:
  - name: default
    run_list:
      - recipe[archiva::nginx_proxy]
