# Disable encoding requirement
Encoding:
  Enabled: false

# The default 79 character limit is sometimes unproductive.
LineLength:
  Max: 100

# Aligning arguments makes for better readability
SpaceBeforeFirstArg:
  Enabled: false
