---
language: ruby
dist: xenial
sudo: false
if: (type = pull_request) OR (tag IS present) OR (branch = master)
cache:
  directories:
    - "$HOME/.berkshelf"
services: docker
install:
  - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current -P chefdk -v 3
  - eval "$(chef shell-init bash)"
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
    -N DOCKER )
  - chef --version
env:
  global:
    - CHEF_LICENSE='accept'
jobs:
  include:
    - stage: Verify
      script: delivery local verify
      env:
        - CHEF_VERSION=14
    - stage: Verify
      script: delivery local verify
      env:
        - CHEF_VERSION=15

    - stage: 'Acceptance: default-ubuntu-1604'
      script: kitchen test default-ubuntu-1604
      env:
        - CHEF_VERSION=14
    - stage: 'Acceptance: default-ubuntu-1604'
      script: kitchen test default-ubuntu-1604
      env:
        - CHEF_VERSION=15

    - stage: 'Acceptance: default-ubuntu-1804'
      script: kitchen test default-ubuntu-1804
      env:
        - CHEF_VERSION=14
    - stage: 'Acceptance: default-ubuntu-1804'
      script: kitchen test default-ubuntu-1804
      env:
        - CHEF_VERSION=15

    - stage: 'Acceptance: default-debian-9'
      script: kitchen test default-debian-9
      env:
        - CHEF_VERSION=14
    - stage: 'Acceptance: default-debian-9'
      script: kitchen test default-debian-9
      env:
        - CHEF_VERSION=15

    - stage: 'Acceptance: default-debian-10'
      script: kitchen test default-debian-10
      env:
        - CHEF_VERSION=14
    - stage: 'Acceptance: default-debian-10'
      script: kitchen test default-debian-10
      env:
        - CHEF_VERSION=15

notifications:
  slack:
    secure: K85DFv64uqlJSDRpQBK7OvrU+05YO52zX5GwhAyqSiuuJlSg+CfEJiBJgfvrB+McVyzmMqmjLnhR2X7TYdeB/dZZoJpRUEyl2qt66AgAG0pl92MCjtdDi+KDgXA0W6nRvLIatDkWyubvgQ+NSFL0dLlNs2z1tqOnYoNuExpME7k=
